# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "taskmapper"
  s.version = "0.8.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["kiafaldorius", "Sirupsen", "deadprogrammer"]
  s.date = "2013-04-01"
  s.description = "TaskMapper provides a universal API to ticket tracking and project management systems."
  s.email = "info@hybridgroup.com"
  s.executables = ["tm"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md",
    "TODO"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "NOTES",
    "README.md",
    "Rakefile",
    "TODO",
    "VERSION",
    "bin/tm",
    "examples/tm_example.rb",
    "examples/tm_example_2.rb",
    "examples/tm_example_3.rb",
    "examples/tm_example_4.rb",
    "lib/taskmapper.rb",
    "lib/taskmapper/authenticator.rb",
    "lib/taskmapper/cli/commands/config.rb",
    "lib/taskmapper/cli/commands/console.rb",
    "lib/taskmapper/cli/commands/generate.rb",
    "lib/taskmapper/cli/commands/generate/provider.rb",
    "lib/taskmapper/cli/commands/generate/provider/comment.rb",
    "lib/taskmapper/cli/commands/generate/provider/project.rb",
    "lib/taskmapper/cli/commands/generate/provider/provider.rb",
    "lib/taskmapper/cli/commands/generate/provider/ticket.rb",
    "lib/taskmapper/cli/commands/help.rb",
    "lib/taskmapper/cli/commands/help/config",
    "lib/taskmapper/cli/commands/help/console",
    "lib/taskmapper/cli/commands/help/generate",
    "lib/taskmapper/cli/commands/help/help",
    "lib/taskmapper/cli/commands/help/project",
    "lib/taskmapper/cli/commands/help/ticket",
    "lib/taskmapper/cli/commands/project.rb",
    "lib/taskmapper/cli/commands/ticket.rb",
    "lib/taskmapper/cli/common.rb",
    "lib/taskmapper/cli/init.rb",
    "lib/taskmapper/comment.rb",
    "lib/taskmapper/common.rb",
    "lib/taskmapper/dummy/comment.rb",
    "lib/taskmapper/dummy/dummy.rb",
    "lib/taskmapper/dummy/project.rb",
    "lib/taskmapper/dummy/ticket.rb",
    "lib/taskmapper/exception.rb",
    "lib/taskmapper/helper.rb",
    "lib/taskmapper/project.rb",
    "lib/taskmapper/provider.rb",
    "lib/taskmapper/tester/comment.rb",
    "lib/taskmapper/tester/project.rb",
    "lib/taskmapper/tester/tester.rb",
    "lib/taskmapper/tester/ticket.rb",
    "lib/taskmapper/ticket.rb",
    "spec/project_spec.rb",
    "spec/rcov.opts",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/taskmapper-cli_spec.rb",
    "spec/taskmapper-exception_spec.rb",
    "spec/taskmapper_spec.rb",
    "spec/ticket_spec.rb",
    "taskmapper.gemspec"
  ]
  s.homepage = "http://ticketrb.com"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "TaskMapper provides a universal API to ticket tracking and project management systems."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activeresource>, ["~> 3.0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0"])
      s.add_runtime_dependency(%q<hashie>, ["~> 2.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.5"])
      s.add_development_dependency(%q<rcov>, ["~> 1.0"])
    else
      s.add_dependency(%q<activeresource>, ["~> 3.0"])
      s.add_dependency(%q<activesupport>, ["~> 3.0"])
      s.add_dependency(%q<hashie>, ["~> 2.0"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8"])
      s.add_dependency(%q<simplecov>, ["~> 0.5"])
      s.add_dependency(%q<rcov>, ["~> 1.0"])
    end
  else
    s.add_dependency(%q<activeresource>, ["~> 3.0"])
    s.add_dependency(%q<activesupport>, ["~> 3.0"])
    s.add_dependency(%q<hashie>, ["~> 2.0"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8"])
    s.add_dependency(%q<simplecov>, ["~> 0.5"])
    s.add_dependency(%q<rcov>, ["~> 1.0"])
  end
end

