require_relative 'repositories/repository'
require_relative 'repositories/entity_repository'
require_relative 'repositories/projects'
require_relative 'repositories/tasks'
require_relative 'repositories/task_comments'
